## Service msg for all the info needed by ROSEE Grasp Planner

# Providing this info is necessary for heri Hal so it knows for which pose it should compute the reqeusted matrices

float32[] motor_positions
float32[] motor_positions_reference
std_msgs/Float32MultiArray finger_joint_positions #in a finger, the phalange joints order must be from the base finger to the tip

---

#all the subsequent info will follow the order specified in motors_names and fingertips_names
string[] fingers_names
string[] motors_names

std_msgs/Float32MultiArray transmission_matrix

std_msgs/Float32MultiArray[] transmission_square_matrices

# The matrices introduces because motor is not the first finger joint,
# computed as transmission_square_matrice ^-T * T*
std_msgs/Float32MultiArray[] transmission_augmented_matrices


std_msgs/Float32MultiArray[] tips_jacobians_normal 
std_msgs/Float32MultiArray[] tips_jacobians_friction
#note: third componet of force is trascurable

float32[] tips_forces_normal
float32[] tips_forces_friction
#note: third componet of force is trascurable

float32[] motors_stiffness
float32[] tips_frictions
float32[] motors_torque_limits
